---
- hosts: localhost 
  connection: local
  become: true


  tasks:
    
  - name: install additional repos 
    package:
      name:
        - void-repo-nonfree
        - void-repo-multilib
        - void-repo-multilib-nonfree
      update_cache: yes
  - include_tasks: packages/packages_utilities.yml	
  - name: install multiple package 
    package:
      name:
        - keepassxc
        - chromium
        - epiphany
        - icecat
        - firefox-esr
        - filezilla
        - texmaker
        - libreoffice
        - dconf-editor
        - zenity 
        - dislocker
        - gparted
        - gnupg
        - pdftk
        - git-cola
        - vlc
        - menulibre
        - texlive-full
        - geeqie
        - darktable
        - flatpak
        - octoxbps
        - gnupg2-scdaemon
        - gksu
        - ulauncher
        - void-docs
        - xdg-user-dirs 
        - base-devel
        - arc-icon-theme
        - arc-theme
        - breeze-cursors
        - papirus-icon-theme
        - xclip 
        - blueman
        - bluez
        - thunderbird
        - python3-devel
        - VeraCrypt
        - Signal-Desktop
        - youtube-dl
        - pluma
        - timeshift
        - yadm
      update_cache: yes    
         
  - name: copy .bashrc file   
    copy:
     src: files/bashrc
     dest: /home/user/.bashrc
     owner: user
     group: user

  - name: import public key  
    command: gpg --import files/pub.key
    
    
  - name: Auto start ulauncher
    copy:
      src: files/ulauncher.desktop
      dest: /home/user/.config/autostart/ulauncher.desktop
      owner: user
      group: user
      mode: 0600
      
  - name: Config GPG-Agent
    copy:
      src: files/gpg-agent.conf
      dest: /home/user/.gnupg/gpg-agent.conf
      owner: user
      group: user
      mode: 0600      
  
  - include_tasks: config/keybindings.yml
  - include_tasks: config/locale.yml
  - include_tasks: config/terminal.yml
  - include_tasks: config/caja.yml
  - include_tasks: config/workspace_settings.yml
