---
- hosts: localhost 
  connection: local
  become: true


  tasks:
  - command: "{{ ansible_python_interpreter | default('/usr/bin/python') }} -c 'import {{ module }}; 	     print({{ module }}.__version__)'"
    vars:
      module: psycopg2
    register: test
  - debug:
      var: test.stdout
  - name: install additional repos 
    package:
      name:
        - void-repo-nonfree
        - void-repo-multilib
        - void-repo-multilib-nonfree
      update_cache: yes
  - include_tasks: packages/packages_utilities.yml      
  - include_tasks: packages/packages_Applications.yml		
  - include_tasks: config/keybindings.yml
#  - include_tasks: config/locale.yml
  - include_tasks: config/terminal.yml
  - include_tasks: config/caja.yml
  - include_tasks: config/workspace_settings.yml
  - include_tasks: service.yml	    
  - include_tasks: config/panel.yml	 
   
  - name: copy .bashrc file   
    copy:
     src: files/bashrc
     dest: /home/user/.bashrc
     owner: user
     group: user

  - name: import public key  
    command: gpg --import files/pub.key
    
  
  - name: Auto start ulauncher
    copy:
      src: files/ulauncher.desktop
      dest: /home/user/.config/autostart/ulauncher.desktop
      owner: user
      group: user
      mode: 0600
      
  - name: Config GPG-Agent
    copy:
      src: files/gpg-agent.conf
      dest: /home/user/.gnupg/gpg-agent.conf
      owner: user
      group: user
      mode: 0600      
  - name: copy appimage launcher 
    copy: src=files/{{ item }} dest=/home/user/.local/share/applications/
    with_items:
    - joplin.desktop
    - etcher.desktop
    - ledger_live.desktop
    - onlyoffice.desktop
    - stacer.desktop

  - name: copy udev rules for yubikey 
    copy: src=files/{{ item }} dest=/etc/udev/rules.d/
    with_items:
    - 69-yubikey.rules
    - 70-u2f.rules
    - 70-yubikey.rules



